---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: hms-rq
  namespace: hms
spec:
  hard: 
    requests.cpu: "5"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi
    pods: "10"
    count/deployments.extensions: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: hms-lr
  namespace: hms
spec:
  limits:
  - default:
      cpu: "800m"
      memory: "800Mi"
    defaultRequest:
      cpu: "800m"
      memory: "800Mi"
    max:
      cpu: "800m"
      memory: "800Mi"
    min:
      cpu: "100m"
      memory: "100Mi"
    type: Container